######################################################################
# Automatically generated by qmake (3.0) Fri Sep 26 12:48:03 2014
######################################################################

TEMPLATE = app
TARGET = argument_list
INCLUDEPATH += .

# Input
HEADERS +=
SOURCES += main.cpp argumentlist.cpp

# Widgets and QDataStream
QT += core widgets

# derp
CONFIG += c++11
